[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fire-notifications"
authors = [{name = "Dale Nguyen", email = "dale@dalenguyen.me"}]
dynamic = ["version", "description"]
